#!/bin/bash

if [ -z $RGP_MAX_DEPTH ]; then
    RGP_MAX_DEPTH=3
fi

if [[ -n $1 && "$1" =~ ^[0-9]+$ ]]; then
    RGP_MAX_DEPTH=$1
fi

function git-recursive-pull {
  if [ `dirs -p | wc -l` -gt $RGP_MAX_DEPTH ]; then
    return
  fi

  for f in *; do
    if [ -d "$f" ]; then
      pushd "$f" > /dev/null
      if [ -d .git ]; then
        echo -e "\x1B[1;31m--\x1B[0m git pull -> \x1B[0;36m$f\x1B[0m [$(git branch | sed -e 's/ //' | sed -e :a -e '$!N; s/\*[ ]*\([^ ]*\)/\\x1B\[1;31m\1\\x1B\[0m/; s/\n/ /; ta')]"
        git pull --rebase
      else
        git-recursive-pull
      fi
      popd > /dev/null
    fi
  done
}
