#!/bin/bash

source ~/.bash/functions

export EDITOR=/usr/bin/vim
set -o vi

export COPYFILE_DISABLE=true

#   Avoid succesive duplicates in the bash command history.
#   ------------------------------------------------------------
export HISTCONTROL=ignoredups

#   Set default blocksize for ls, df, du
#   from this: http://hints.macworld.com/comment.php?mode=view&cid=24491
#   ------------------------------------------------------------
export BLOCKSIZE=1k

#   Add color to terminal
#   ------------------------------------------------------------
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad