#!/bin/bash

source ~/.bash/functions

export HOST=$(hostname)

#   ------------------------
#     MAKE TERMINAL BETTER
#   ------------------------

register_alias rm "rm -i"                            # Preferred 'rm' implementation
register_alias grep "grep --color=auto"              # Preferred 'grep' implementation
register_alias egrep "egrep --color=auto"            # Preferred 'egrep' implementation
register_alias fgrep "fgrep --color=auto"            # Preferred 'fgrep' implementation
register_alias cp 'cp -iv'                           # Preferred 'cp' implementation
register_alias mv 'mv -iv'                           # Preferred 'mv' implementation
register_alias mkdir 'mkdir -pv'                     # Preferred 'mkdir' implementation
register_alias ll 'ls -Flhp'                         # ll:           Powerfull ls
register_alias less 'less -FSRXc'                    # Preferred 'less' implementation
register_alias which 'type -all'                     # which:        Find executables

#   --------------
#     NETWORKING
#   --------------
register_alias netCons 'lsof -i'                             # netCons:      Show all open TCP/IP sockets
register_alias flushDNS 'dscacheutil -flushcache'            # flushDNS:     Flush out the DNS Cache
register_alias lsock 'sudo /usr/sbin/lsof -i -P'             # lsock:        Display open sockets
register_alias lsockU 'sudo /usr/sbin/lsof -nP | grep UDP'   # lsockU:       Display only open UDP sockets
register_alias lsockT 'sudo /usr/sbin/lsof -nP | grep TCP'   # lsockT:       Display only open TCP sockets
register_alias ipInfo0 'ipconfig getpacket en0'              # ipInfo0:      Get info on connections for en0
register_alias ipInfo1 'ipconfig getpacket en1'              # ipInfo1:      Get info on connections for en1
register_alias openPorts 'sudo lsof -i | grep LISTEN'        # openPorts:    All listening connections
register_alias showBlocked 'sudo ipfw list'                  # showBlocked:  All ipfw rules inc/ blocked IPs
