#!/bin/bash

source ~/.bash/functions

register_alias mysql '/usr/local/mysql/bin/mysql'
register_alias mysqladmin '/usr/local/mysql/bin/mysqladmin'
register_alias mysqldump '/usr/local/mysql/bin/mysqldump'
