#!/bin/bash

source ~/.bash/functions

register_alias netstat-nap 'lsof -iTCP -sTCP:LISTEN -n -P'

#   cleanupDS:  Recursively delete .DS_Store files
#   -------------------------------------------------------------------
register_alias cleanupDS "find . -type f -name '*.DS_Store' -ls -delete"


#   cleanupLS:  Clean up LaunchServices to remove duplicates in the "Open With" menu
#   -----------------------------------------------------------------------------------
register_alias cleanupLS "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"
