#!/bin/bash

source ~/.bash/functions

register_alias f 'open -a Finder ./'                 # f:            Opens current directory in MacOS Finder
function trash() { command mv "$@" ~/.Trash ; }      # trash:        Moves a file to the MacOS trash
function ql() { qlmanage -p "$*" >& /dev/null; }     # ql:           Opens any file in MacOS Quicklook Preview
register_alias DT 'tee ~/Desktop/terminalOut.txt'    # DT:           Pipe content to file on MacOS Desktop

register_alias netstat-nap 'lsof -iTCP -sTCP:LISTEN -n -P'

#   cdf:  'Cd's to frontmost window of MacOS Finder
#   ------------------------------------------------------
function cdf() {
    currFolderPath=$( /usr/bin/osascript <<EOT
            tell application "Finder"
                try
            set currFolder to (folder of the front window as alias)
                on error
            set currFolder to (path to desktop folder as alias)
                end try
                POSIX path of currFolder
            end tell
EOT
    )
    echo "cd to \"$currFolderPath\""
    cd "$currFolderPath"
}

#   spotlight: Search for a file using MacOS Spotlight's metadata
#   -----------------------------------------------------------
function spotlight() { mdfind "kMDItemDisplayName == '$@'wc"; }

#   cleanupDS:  Recursively delete .DS_Store files
#   -------------------------------------------------------------------
register_alias cleanupDS "find . -type f -name '*.DS_Store' -ls -delete"

#   finderShowHidden:   Show hidden files in Finder
#   finderHideHidden:   Hide hidden files in Finder
#   -------------------------------------------------------------------
register_alias finderShowHidden 'defaults write com.apple.finder ShowAllFiles TRUE'
register_alias finderHideHidden 'defaults write com.apple.finder ShowAllFiles FALSE'

#   cleanupLS:  Clean up LaunchServices to remove duplicates in the "Open With" menu
#   -----------------------------------------------------------------------------------
register_alias cleanupLS "/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder"

register_alias screensaver "/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine -background &"

if [ -x /usr/local/bin/brew ] && [ -f $(brew --prefix)/bin/gdate ]; then
    register_alias date "gdate"
fi
