#!/bin/bash

source ~/.bash/functions

local self_dir=$(script_path $BASH_SOURCE[0])
source $self_dir/utils

function __jenv_prompt {
    command -v brew > /dev/null 2>&1 || return

    local _global_jenv_name=$(jenv global 2>&1)
    local _local_jenv_name=$(jenv local 2>&1)
    local _shell_jenv_name=$(jenv shell 2>&1)
    if [[ -n ${_global_jenv_name} ]]; then
	    if [[ ${_shell_jenv_name} != "jenv: no shell-specific version configured"
	       && ${_shell_jenv_name} != ${_global_jenv_name}  ]]; then
	        printf "(${_shell_jenv_name}) "
	    elif [[ ${_local_jenv_name} != "jenv: no local version configured for this directory"
	    	 && ${_local_jenv_name} != ${_global_jenv_name}  ]]; then
	        printf "(${_local_jenv_name}) "
	    fi
	fi
}
